# Generated by Django 4.2 on 2023-04-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actuator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("subsystem", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=200)),
                ("subsystem", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SensorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        db_column="name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subsystem.sensor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActuatorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=200)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.ForeignKey(
                        db_column="name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="subsystem.actuator",
                    ),
                ),
            ],
        ),
    ]
