# Generated by Django 4.2 on 2023-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subsystem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actuator",
            name="unique_name",
            field=models.CharField(default="new", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actuator",
            name="unit",
            field=models.CharField(default="not", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensor",
            name="unique_name",
            field=models.CharField(default="not", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensor",
            name="unit",
            field=models.CharField(default="not", max_length=200),
            preserve_default=False,
        ),
    ]
