# Generated by Django 4.2 on 2023-04-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subsystem", "0002_actuator_unique_name_actuator_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="actuator", name="unique_name",),
        migrations.RemoveField(model_name="actuator", name="unit",),
        migrations.RemoveField(model_name="sensor", name="unique_name",),
        migrations.RemoveField(model_name="sensor", name="unit",),
    ]
